### ISSUE TITLE
have_attribue matcher not working when using a different key format

### ISSUE THREAD

**Issue by bdubaut** [G5/jsonapi-resources-matchers#2]
The default configuration of the jsonapi_resources gem is to have dasherized keys:
```ruby
config.json_key_format = :dasherized_key
```
However, when  using another type of keys, for example camelized keys, the `have_attribute` matcher does not pick them up (see [here](https://github.com/G5/jsonapi-resources-matchers/blob/master/lib/jsonapi/resources/matchers/have_attribute.rb#L19)).

It would be nice if most key formats were supported:
- `underscored_key`, 
- `camelized_key`,
- `dasherized_key`

I can understand that custom key formats should not be supported out of the box by this gem.

I don't have the time to look into this right now, hopefully I will be able to propose a pull request soon if no-one has already solved this by then.

**Comment by ramontayag** [comment]
@bdubaut would love a pull request! That's right - we're only using the defaults of jsonapi-resources so didn't build for all features.

**Comment by bdubaut** [comment]
@ramontayag I tried to look into it, but unfortunately the build is failing from the start as the dummy app appears to be too old and the specs won't run:
```
$ bundle exec rake
/home/travis/.rvm/rubies/ruby-2.2.2/bin/ruby -I/home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib:/home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-support-3.5.0/lib /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb
DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = true` instead.
 (called from block in <top (required)> at /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/dummy/config/environments/test.rb:16)
DEPRECATION WARNING: `config.static_cache_control` is deprecated and will be removed in Rails 5.1.
Please use
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=3600' }`
instead.
 (called from block in <top (required)> at /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/dummy/config/environments/test.rb:17)
/home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x000000030202f8> (NoMethodError)
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/dummy/config/initializers/assets.rb:4:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/activesupport-5.0.0/lib/active_support/notifications.rb:166:in `instrument'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/engine.rb:647:in `load_config_initializer'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/engine.rb:611:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:30:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/travis/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/railties-5.0.0/lib/rails/application.rb:352:in `initialize!'
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/dummy/config/environment.rb:5:in `<top (required)>'
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/spec_helper.rb:2:in `require'
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/spec_helper.rb:2:in `<top (required)>'
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/jsonapi/resources/matchers/filter_spec.rb:1:in `require'
	from /home/travis/build/bdubaut/jsonapi-resources-matchers/spec/jsonapi/resources/matchers/filter_spec.rb:1:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:100:in `setup'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:86:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:71:in `run'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/exe/rspec:4:in `<main>'
/home/travis/.rvm/rubies/ruby-2.2.2/bin/ruby -I/home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/lib:/home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-support-3.5.0/lib /home/travis/.rvm/gems/ruby-2.2.2/gems/rspec-core-3.5.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I tried updating the gems, but nothing changes. removing the `config.assets` lines in the configs don't change anything either, it just triggers another error (from `ActionDispatch` this time).

Do you have any idea how to fix this ?

**Comment by ramontayag** [comment]
@bdubaut ok let me check. It's probably just gems that are installed now are new and incompatible.

**Comment by ramontayag** [comment]
Ok latest master specs pass. I locked development version of Rails to ~> 4, and jsonapi-resources to >= 0.6.0

**Comment by jfcartkeep** [comment]
@ramontayag this PR #3 should fix this issue. Can you validate this?

**Comment by ramontayag** [comment]
Yes, looks good! Thanks.
